#!/bin/bash -e

if [ $# -lt 1 ];then
    echo "USAGE: $0 [etcd_nodes...]"
    exit 1
fi

for etcdNode in $@;do

    echo "devclear: $etcdNode"

    vagrant ssh -c "sudo systemctl stop etcd2{,-backup}.service; \
sudo rm -rf /var/lib/etcd2/member \
" "$etcdNode"
done
