#!/bin/bash -e

if [ $# -lt 1 ];then
    echo "USAGE: $0 [etcd_nodes...]"
    exit 1
fi

for etcdNode in $@;do
    echo "---${etcdNode}---"
    vagrant ssh -c "etcdctl member list" $etcdNode
    echo "---------------------"
done
