#!/bin/bash

if [ $# -lt 1 ];then
    echo "USAGE: $0 [machines...]"
    exit 1
fi
for i in $@;do
    echo "STOPPING ${i}"
    vagrant ssh -c "sudo systemctl stop etcd2.service etcd2-backup.{timer,service}" "$i"
done

mcnt=0
for i in $@;do
    if [ $mcnt -eq 0 ];then
	echo "RESTORING ${i} first"
	vagrant ssh -c "sudo systemctl start etcd2-restore-first.service" "$i"
    else
	echo "JOIN RESTORING ${i}"
	vagrant ssh -c "sudo systemctl start etcd2-restore-join.service" "$i"
    fi
    mcnt=$(( mcnt + 1 ))
done
sleep 10
for i in $@;do
        echo "STARTING ${i}"
    	vagrant ssh -c "sudo systemctl start etcd2.service etcd2-backup.timer" "$i"
done
