#!/bin/bash -e

if [ $# -lt 1 ];then
    echo "USAGE: $0 [etcd_nodes...]"
    exit 1
fi

for etcdNode in $@;do
    echo "devstop: $etcdNode"

    vagrant ssh -c "sudo systemctl stop etcd2-backup.{timer,service} etcd2.service" "$etcdNode"
done
