#!/bin/bash -e

if [ -z $1 ];then
    echo "USAGE: $0 <eX>"
    exit 1
fi

etcdNode=$1

echo "devstop: $etcdNode"

vagrant ssh -c "sudo systemctl stop etcd2-backup.{timer,service} etcd2.service" "$etcdNode"
